### PR TITLE
New Crowdin updates

### PR DESCRIPTION
**Pull request by pokecodebot**

### CODE REVIEW

**Review by Quentinchampenois — APPROVED** [review]

**Comment by Quentinchampenois** [comment]
CI is failing but related issue has been opened

**Review by armandfardeau — APPROVED** [review]

**Comment by paulinebessoles** [comment]
I just want to change some french translations before merging.

**Review by paulinebessoles — CHANGES_REQUESTED** [review]
I just want to change some french translations before merging.

**Review by paulinebessoles — APPROVED** [review]

**Review by armandfardeau — CHANGES_REQUESTED** [review]
Please fix tests

**Pull request merged**
